### PR TITLE
Implement connection checks using PING frame. Task #62

### PR DESCRIPTION
**Pull request by a00920**

### CODE REVIEW

**Comment by vmagamedov** [comment]
Awesome, thanks! I don't have any complains about your implementation, but would you mind to write also a test?

**Comment by a00920** [comment]
@vmagamedov

Tests added.

**Comment by vmagamedov** [comment]
Thanks! But now I need to discover a new way to configure client/server, instead of `ping_delay` and `ping_timeout` arguments, and do this before merging this PR into master.

As you can see [here](https://github.com/grpc/grpc/blob/131d11661bcccbdadc922b67f8b5c58341c37bd3/include/grpc/impl/codegen/grpc_types.h#L137-L401), gRPC Core already has plenty of configuration options. I hope that grpclib will also have similar configuration options in the future.

When I come up with a design of these options I would merge this PR.

**Comment by vmagamedov** [comment]
Turns out there are lots of things to consider:
https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md
https://github.com/grpc/grpc/blob/master/doc/keepalive.md

Current implementation will simply cause a GOAWAY frame (disconnect) from the grpcio-based server, because it sends PING frames so frequently.

**Comment by vmagamedov** [comment]
Merged my WIP `channelz` branch into `master` to make it possible to implement keepalive feature properly. Now we know when last `DATA` frame was sent into connection. Also merged my `config` branch into `master`, now we have `grpclib.config.Configuration` class to configure `grpclib`.

**Comment by a00920** [comment]
started from the beginning in another branch 
https://github.com/vmagamedov/grpclib/pull/96

**Pull request closed without merging**
