### PR TITLE
[BUG] Can't handle long messages

### PR DESCRIPTION
**Pull request by mosquito**
That PR reproduces my issue. Messages with length greater than 65535 handles with error.

### CODE REVIEW

**Comment by vmagamedov** [comment]
Thank you for this bug report!

I think that `grpclib.stream.recv_message` is not guilty for this bug. And there are actually two bugs:
1. Sending party. `grpclib.protocol.Stream#send_data` doesn't honors `h2.connection.H2Connection#max_outbound_frame_size`, which is equal to 16384 and is not a constant and can have any value. So
    ```python
    min(window, f_last - f_pos)
    ```
    should be replaced with
    ```python
    min(window, max_frame_size, f_last - f_pos)
    ```
    in `grpclib.protocol.Stream#send_data`. This is the cause of exceptions like this:
    ```python
    h2.exceptions.FrameTooLargeError: Cannot send frame size 65535, max frame size is 16384
    ```
    where 65535 is a window size and 16384 is a `max_outbound_frame_size`.

2. Receiving party. After this bug was fixed, I've managed to reproduce the second bug, which can be fixed by your changes in `grpclib.stream.recv_message`. But I have to explain why it is not the right place to fix it. The problem is that `grpclib.protocol.Stream#recv_data` acknowledges received data only after requested data size will be fully received. This is was the most primitive way to enable h2 flow control. And when message exceeds window size (65535 by default), sending party will wait for the receiving party forever. The right thing to do is to acknowledge received data in the `grpclib.protocol.Buffer#append` method, and not all the received data, but only received data limited by requested data size.

Would you mind if I will fix these bugs? Or you would like to fix these bugs and update your PR?

**Comment by mosquito** [comment]
Should I create a separate issue?

**Comment by vmagamedov** [comment]
Fixed the first one: 3e4b85ff4f0536c3623ba189049aaadacdb7e09f

**Comment by vmagamedov** [comment]
@mosquito can you check that all these bugs are fixed in 3e4b85ff4f0536c3623ba189049aaadacdb7e09f and 48e0859cb810a929a38e8f46724c05425ee2593e and close this PR?

**Comment by mosquito** [comment]
```Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "asyncio/events.py", line 127, in _run
    self._callback(*self._args)
  File "asyncio/selector_events.py", line 731, in _read_ready
    self._protocol.data_received(data)
  File "site-packages/grpclib/protocol.py", line 435, in data_received
    self.processor.process(event)
  File "site-packages/grpclib/protocol.py", line 358, in process
    proc(event)
  File "site-packages/grpclib/protocol.py", line 384, in process_window_updated
    self.streams[event.stream_id].__window_updated__.set()
KeyError: 1```

**Comment by vmagamedov** [comment]
Yeah, removing stream too early (when it is half-closed on the other side), I'm fixing this...

**Comment by vmagamedov** [comment]
@mosquito I hope this is the last fix) can you confirm that the bug is fixed now?

**Comment by mosquito** [comment]
Well... it's works but 3 times slower then basic `grpcio` with a threadpool. You can reproduce it on my [examples](https://gist.github.com/mosquito/6a14e020c7f5dc0cd6fb1a145da3ef05)

**Comment by vmagamedov** [comment]
It is obvious that you will have noticeable difference when comparing pure-Python code with C/Cython/Python code. UVLoop doesn't helps much, I think that performance is mostly tied to HTTP parsing. For example, `aiohttp` became much faster after rewriting HTTP parser in C.

I assume that `hyper-h2` project will eventually get C or Rust speedups, and then `grpclib` will be automatically faster as well.

In my benchmarks `grpclib` is typically 2x slower than `grpcio`, which is OK for me, because these are not real-world benchmarks, they comparing only "overhead".

**Comment by vmagamedov** [comment]
Closing this PR as fixed, published new release candidate: `grpclib==0.1.0rc2`

**Comment by mosquito** [comment]
Thank you.

**Pull request closed without merging**
